
CREATE TABLE ユーザ(
    ID VARCHAR2(7) PRIMARY KEY NOT NULL,
    パスワード VARCHAR2(255) NOT NULL,
    氏名    VARCHAR2(20) NOT NULL,
    生年月日    DATE NOT NULL,
    クラス  VARCHAR2(3)
);

CREATE TABLE 団体(
    団体ID VARCHAR2(3) PRIMARY KEY NOT NULL,
    ID  VARCHAR(7)  REFERENCES ユーザ(ID), --管理ユーザのID
    団体名  VARCHAR2(100) NOT NULL,
    団体カテゴリ    VARCHAR2(20) NOT NULL
);

CREATE TABLE 権限(
    権限ID VARCHAR2(2) PRIMARY KEY NOT NULL,
    権限名 VARCHAR2(20)
);
CREATE TABLE ユーザ管理(
    ID  VARCHAR2(7) REFERENCES ユーザ(ID),
    団体ID VARCHAR2(3) REFERENCES 団体(団体ID),
    権限ID VARCHAR2(2) REFERENCES 権限(権限ID), 
    PRIMARY KEY (ID,団体ID,権限ID)
);


CREATE TABLE ニュース(
    記事ID NUMBER(3) PRIMARY KEY NOT NULL,
    タイトル VARCHAR2(100) NOT NULL,
    投稿日 DATE NOT NULL,
    本文 VARCHAR2(2000) NOT NULL,
    ID VARCHAR2(7) NOT NULL REFERENCES ユーザ(ID)
);


CREATE TABLE 活動カテゴリ(
    活動カテゴリID NUMBER(3) PRIMARY KEY NOT NULL,
    活動カテゴリ名 VARCHAR2(20) NOT NULL
);

CREATE TABLE 投票ログ(
    活動カテゴリID NUMBER(3) REFERENCES 活動カテゴリ(活動カテゴリID),
    ID  VARCHAR2(7) REFERENCES ユーザ(ID),
    日時    DATE NOT NULL,
    投票先ID VARCHAR2(8),
    PRIMARY KEY (活動カテゴリID,ID)
);

CREATE TABLE CM大会動画(
    動画ID NUMBER(3) PRIMARY KEY NOT NULL,
    団体ID VARCHAR(3) REFERENCES 団体(団体ID),
    動画URL VARCHAR2(500) NOT NULL,
    コメント VARCHAR2(2000) NOT NULL
);

CREATE TABLE 写真(
    写真ID NUMBER(5) PRIMARY KEY NOT NULL,
    ID  VARCHAR2(7) REFERENCES ユーザ(ID) NOT NULL,
    学年    NUMBER(1)   NOT NULL,
    学科ID CHAR(1) NOT NULL,
    クラス  NUMBER(1)   NOT NULL,
    写真URL VARCHAR2(500) NOT NULL,
    公開範囲    NUMBER(1) NOT NULL,
    詳細コメント    VARCHAR2(500) NOT NULL
);

CREATE TABLE キャッチコピー(
    キャッチコピーID NUMBER(3) PRIMARY KEY NOT NULL,
    団体ID VARCHAR2(3)   REFERENCES 団体(団体ID) NOT NULL,
    キャッチコピー VARCHAR2(300) NOT NULL
);

CREATE TABLE 商品カテゴリ(
    カテゴリID NUMBER(2) PRIMARY KEY NOT NULL,
    カテゴリ名 VARCHAR2(30) NOT NULL
);

CREATE TABLE  商品(
    商品ID VARCHAR2(4) PRIMARY KEY NOT NULL,
    商品名 VARCHAR2(30) NOT NULL,
    URL VARCHAR2(300) NOT NULL,
    カテゴリID NUMBER(2) NOT NULL REFERENCES 商品カテゴリ(カテゴリID),
    原価 NUMBER(5) NOT NULL,
    定価 NUMBER(5) NOT NULL,
    売価 NUMBER(5) NOT NULL,
    準備個数 NUMBER(5) NOT NULL
);

CREATE TABLE 商品管理(
    団体ID VARCHAR2(3) REFERENCES 団体(団体ID),
    商品ID VARCHAR2(4) REFERENCES 商品(商品ID),
    PRIMARY KEY(団体ID,商品ID)
);


CREATE TABLE 会計ログ(
    商品ID VARCHAR2(4) REFERENCES 商品(商品ID),
    団体ID VARCHAR2(3) REFERENCES 団体(団体ID),
    個数    NUMBER(3) NOT NULL,
    日付    DATE     NOT NULL,
    ID      VARCHAR2(7) REFERENCES ユーザ(ID) NOT NULL,
    PRIMARY KEY(商品ID,団体ID,日付)
);
CREATE TABLE 企画書(
    団体ID VARCHAR2(3) PRIMARY KEY REFERENCES 団体(団体ID) NOT NULL,
    企画内容 VARCHAR2(2000) NOT NULL,
    外部レンタル機材 VARCHAR2(1000) NOT NULL,
    団体持参物 VARCHAR2(1000) NOT NULL,
    校内設備 VARCHAR2(1000) NOT NULL
);

CREATE TABLE 諸経費区分(
    諸経費区分ID NUMBER(3) PRIMARY KEY NOT NULL,
    諸経費区分名 VARCHAR2(30) NOT NULL
);

CREATE TABLE 諸経費(
    ID NUMBER(4) PRIMARY KEY NOT NULL,
    団体ID VARCHAR(3) REFERENCES 団体(団体ID) NOT NULL,
    諸経費区分ID NUMBER(3) REFERENCES 諸経費区分(諸経費区分ID),
    日付 DATE NOT NULL,
    諸経費名 VARCHAR2(1000) NOT NULL,
    購入場所 VARCHAR2(255) NOT NULL,
    単価 NUMBER(5) NOT NULL, 
    数量 NUMBER(4) NOT NULL,
    数量単位 VARCHAR2(2)
);


CREATE TABLE チェックリスト(
    団体ID VARCHAR2(3) REFERENCES 団体(団体ID) NOT NULL,
    報告書区分 NUMBER(1) NOT NULL,
    担任チェック NUMBER(1) NOT NULL,
    本部チェック NUMBER(1) NOT NULL
);

CREATE TABLE 収支報告書(
    団体ID VARCHAR2(3) REFERENCES 団体(団体ID) NOT NULL,
    売上 NUMBER(5) NOT NULL,
    材料費 NUMBER(5) NOT NULL,
    純利益 NUMBER(5) NOT NULL
);







SELECT table_name FROM user_tables;

